### ISSUE TITLE
unable connect to remote server

### ISSUE THREAD

**Issue by safffat** [m-bers/docker-virt-manager#8]
I want connect to a remote server that have multiple kvm up.
but when it start it stuck on "connecting" without any error!

![image](https://user-images.githubusercontent.com/26141794/139038155-787ba364-2ffb-45da-9a91-c205e881e8d7.png)

what should i do?

also i'm able to connect to that server with virt-manager but it's not available on docker-virt-manager.

docker-compose:

```
services: 
  virt-manager:
    image: mber5/virt-manager:latest
    restart: always
    ports:
      - 8185:80
      - 7681:7681

    environment:
      HOSTS: "['qemu+ssh://ghaderi@91.98.100.225/system']"

    volumes:
      - /home/ubuntu/.ssh/id_rsa:/root/.ssh/id_rsa:ro
```
