### ISSUE TITLE
Error connecting to graphical console

### ISSUE THREAD

**Issue by GentleHoneyLover** [m-bers/docker-virt-manager#9]
Thanks for the container! The idea is brilliant!

I have an issue, though. Container starts and I can make the connection (to qemu:///session). I can see my VMs and can start and stop them. However, when I try to open any VM I get `Error connecting to graphical console: Failed to recv file descriptor: Permission denied`.

<img width="1044" alt="Screen Shot 2021-12-05 at 19 03 26" src="https://user-images.githubusercontent.com/38346023/144758247-1987010e-e962-4b80-9ae3-1ba30e3a8a4d.png">

I'm running Ubuntu 20.04 on the host. I can successfully connect to all my VMs via a remote virtual-manager connection from another Ubuntu machine — so my QEMU/KVM config should be fine I guess.

What could I be missing here? Pleas point me to the right direction! Thanks in advance!

Here's my docker-compose:

```
  virt-manager:
    container_name: virt-manager
    image: docker.io/mber5/virt-manager
    restart: unless-stopped
    environment:
      - DARK_MODE=false
      - HOSTS="['qemu:///session']"
    ports:
      - 8185:80
    volumes:
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
      - /var/lib/libvirt/images:/var/lib/libvirt/images
    devices:
      - /dev/kvm:/dev/kvm
```
